# use this file for encrypted user/password information.
# Unencrypted values may be used in this file using standard yaml syntax
# Encrypted values must be enclosed in ![] within the quotes.
# API specification



#Salesforce Configurations    
sfdc:   
  token: "![Bwh7z08eUXR0JktiKrCw9q8e9DfnQo3yEKHAaT3626k=]"
  password : "![7M4iZ7XsCsuZSk9vHzofXQ==]"
    
